name: Update repo's and AUR's PKGBUILD

on:
  push:
  schedule: 
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: install dependencies
        run: |
          pacman -Syu
          pacman -S git binutils python python-pip openssl openssl-1.1 python-pipx --noconfirm

      - name: install required python modules
        run: |
          pipx install shyaml

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: create user
        run: |
          useradd -m homlet

      - name: update PKGBUILD
        run: |
          git clone https://github.com/project-slippi/slippi-launcher /tmp/slippi-launcher
          cd /tmp/slippi-launcher
          curl -L https://github.com/project-slippi/slippi-launcher/releases/latest/download/latest-linux.yml > latest-linux.yml
          TAGNAME="$(cat latest-linux.yml | /github/home/.local/bin/shyaml get-value version)"
          SHA="$(echo -n $(cat latest-linux.yml | /github/home/.local/bin/shyaml get-value sha512) | base64 --decode | hexdump -ve '1/1 "%.2x"')"
          git checkout --quiet "$(git rev-list -n 1 v$TAGNAME)"
          PKGVER="$(git describe --long --tags | sed -e 's/-\([^-]*-g[^-]*\)$/-r\1/' -e 's/-/./g')"
          cd -

          sed -i "/_tagname=/c\_tagname=\'$TAGNAME\'" ./PKGBUILD
          sed -i "/pkgver=/c\pkgver=\'$PKGVER\'" ./PKGBUILD
          sed -i "/sha512sums=/c\sha512sums=(\'$SHA\')" ./PKGBUILD

          chown -R homlet:homlet .
          su -c "makepkg --printsrcinfo > .SRCINFO" homlet
          chown -R root:root .

      - name: push changes to repo
        run: |
          git config --global user.name 'HamletDuFromage'
          git config --global user.email '61667930+HamletDuFromage@users.noreply.github.com'
          git add PKGBUILD .SRCINFO
          if [[ `git status --porcelain` ]]; then
            git commit -m "automatic: updated PKGBUILD (repo)"
            git push
          else
            echo "Nothing to commit! (repo)"
          fi

  update-aur:
    needs: update-repo
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.AUR_SSH_PRIVATE_KEY }}"

      - name: push changes to aur
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            git clone ssh://aur@aur.archlinux.org/slippi-launcher.git /tmp/aur
            cp {PKGBUILD,.SRCINFO} /tmp/aur/
            cd /tmp/aur
            git config --global user.name 'HamletDuFromage (github workflow https://github.com/HamletDuFromage/slippi-launcher-PKGBUILD)'
            git config --global user.email '61667930+HamletDuFromage@users.noreply.github.com'
            git add PKGBUILD .SRCINFO
            if [[ `git status --porcelain` ]]; then
              git commit -m "automatic: updated PKGBUILD (AUR)"
              git push
            else
              echo "Nothing to commit! (AUR)"
            fi
